### ISSUE TITLE
uni app 使用presetAttributify预设 打包H5异常

### ISSUE THREAD

**Issue by tangerball** [MellowCo/unocss-webpack-uniapp2#4]
```
import presetWeapp from 'unocss-preset-weapp'
import { presetUno, presetAttributify, presetIcons } from 'unocss'
import { extractorAttributify, transformerClass } from 'unocss-preset-weapp/transformer'

const { transformerAttributify, presetWeappAttributify } = extractorAttributify()

export default {
  theme: {
    // 解决小程序不支持 * 选择器
    preflightRoot: ['page,::before,::after'],
  },
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons(),
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp({
      // h5兼容
      // 只开发小程序可删除
      platform: 'uniapp',
      isH5: process.env.UNI_PLATFORM === 'h5',
    }),

    // attributify autocomplete
    presetWeappAttributify(),
  ],
  transformers: [
    // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify
    transformerAttributify(),

    // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass
    transformerClass(),
  ],
}

```

配置 presetAttributify 预设会出现H5打包异常

```
static/js/index.4309df75.js from Terser plugin
Unexpected token name «_wn_2979ff», expected punc «,» [static/js/index.4309df75.js:178,81296]       
    at js_error (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:549:11)
    at croak (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:1273:9)
    at token_error (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:1281:9)        
    at expect_token (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:1294:9)       
    at expect (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:1297:36)
    at expr_list (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2602:44)
    at D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2620:23
    at _embed_tokens_wrapper (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:1338:26)
    at expr_atom (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2506:35)
    at maybe_unary (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3423:19)       
    at expr_ops (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3474:24)
    at maybe_conditional (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3479:20) 
    at maybe_assign (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3556:20)      
    at expression (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3581:24)        
    at call_args (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3399:27)
    at subscripts (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3312:30)        
    at subscripts (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3286:29)        
    at expr_atom (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2563:20)
    at maybe_unary (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3423:19)       
    at expr_ops (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3474:24)
    at maybe_conditional (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3479:20) 
    at maybe_assign (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3556:20)      
    at expression (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3581:24)        
    at simple_statement (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:1586:55)  
    at statement (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:1399:19)
    at _embed_tokens_wrapper (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:1338:26)
    at block_ (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2177:20)
    at _function_body (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2089:21)    
    at function_ (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:1731:20)
    at expr_atom (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2523:24)
    at maybe_unary (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3423:19)       
    at expr_ops (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3474:24)
    at maybe_conditional (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3479:20) 
    at maybe_assign (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3556:20)      
    at expression (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3581:24)        
    at params_or_seq_ (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2053:24)    
    at expr_atom (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2471:29)
    at maybe_unary (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3423:19)       
    at expr_ops (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3474:24)
    at maybe_conditional (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3479:20) 
    at maybe_assign (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3556:20)      
    at expression (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3581:24)        
    at object_or_destructuring_ (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2670:25)
    at _embed_tokens_wrapper (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:1338:26)
    at expr_atom (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2508:35)
    at maybe_unary (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3423:19)       
    at expr_ops (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3474:24)
    at maybe_conditional (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3479:20) 
    at maybe_assign (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3556:20)      
    at expression (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3581:24)        
    at params_or_seq_ (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2053:24)    
    at expr_atom (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:2471:29)
    at maybe_unary (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3423:19)       
    at expr_ops (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3474:24)
    at maybe_conditional (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3479:20) 
    at maybe_assign (D:\mCodeBase\wsy-template\node_modules\terser\dist\bundle.min.js:3556:20) 
```

**Comment by MellowCo** [comment]
就是因为小程序不支持 presetUno, presetAttributify，才有的presetWeapp预设哦

**Comment by tangerball** [comment]
> 就是因为小程序不支持presetUno、presetAttributify，补充的presetWeapp默认哦

presetIcons 这块会有影响的吗？
